
export enum AppStage {
  LANDING = 'LANDING',
  PATH_FINDER = 'PATH_FINDER',
  REGISTRATION = 'REGISTRATION',
  DASHBOARD = 'DASHBOARD',
  LEVEL_CONTENT = 'LEVEL_CONTENT',
  CERTIFICATE = 'CERTIFICATE'
}

export interface UserProfile {
  name: string;
  startupName: string;
  startupDescription: string;
  industry: string;
}

export interface Question {
  id: number;
  text: string;
  options: string[];
  correctIndex: number;
  explanation?: string; // Brief explanation for the correct answer
}

export interface LevelData {
  id: number;
  title: string;
  description: string;
  isLocked: boolean;
  isCompleted: boolean;
  content?: string; // Markdown/Text content generated by AI
  exercisePrompt?: string; // The exercise question
  quiz?: Question[]; // The quiz questions
}

export const LEVELS_CONFIG = [
  { id: 1, title: 'الفكرة والتحقق (Ideation)', description: 'صقل الفكرة والتحقق من المشكلة والحل.' },
  { id: 2, title: 'نموذج العمل (Business Model)', description: 'بناء مخطط نموذج العمل التجاري (BMC).' },
  { id: 3, title: 'تحليل السوق (Market Analysis)', description: 'فهم الجمهور المستهدف والمنافسين.' },
  { id: 4, title: 'المنتج الأولي (MVP)', description: 'تطوير الحد الأدنى من المنتج القابل للتطبيق.' },
  { id: 5, title: 'المالية والقانونية (Finance & Legal)', description: 'التوقعات المالية والهيكل القانوني.' },
  { id: 6, title: 'العرض والتمويل (Pitching)', description: 'تجهيز عرض المستثمرين واستراتيجيات التمويل.' },
];
